### ISSUE TITLE
Why adds are removed

### ISSUE THREAD

**Issue by franpog859** [zmofei/zhuwenlong.com-frontend#4]
Why did you decide to remove the ads which use `react-adsense`? I'm trying to find some good references of its usage and I see many repos decided to get rid of them

**Comment by zmofei** [comment]
I meat 2 issues:
* The ad is not in the right position: While I put the ad component in some place of the page, but the result is the ad not show in the target place.
* The ad didn't show after we re-render the component: I put the ad in the block list, but if I change to another page(rerender the list with new data) the ad will not show.

**Comment by franpog859** [comment]
Cool, thanks a lot for the information 🎉
